services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voxlet-backend
    environment:
      DB_NAME: VoxletDB
      DB_USER: voxlet
      DB_PWORD: ALSO_CHANGE_ME
      DB_IP: mariadb
      DB_PORT: ":3306"
      BACKEND_API_PORT: ":3000"
    ports:
      - "3000:3000"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  mariadb:
    image: mariadb:lts
    container_name: voxlet-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: CHANGE_ME
      MARIADB_DATABASE: VoxletDB
      MARIADB_USER: voxlet
      MARIADB_PASSWORD: ALSO_CHANGE_ME
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "3306:3306"
  
  redis:
    image: redis:trixie
    container_name: voxlet-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "6379:6379"